### ISSUE TITLE
digits only values in text columns cause trouble when using sqlite

### ISSUE THREAD

**Issue by rbauduin** [jacentino/DbFun#1]
Here's how to reproduce it:

First setup the database:
```
 echo "CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, login string); insert into users(login) VALUES ('743278427838');" | sqlite3 db.sqlite
 ```
 
 Then, in the same directory, execute this script with `dotnet fsi`:
```
#r "nuget: DbFun.Core, 1.1.0"
#r "nuget: System.Data.SQLite, 1.0.119"

open DbFun.Core
open DbFun.Core.Builders
open System.Data
open System.Data.SQLite
open DbFun.Core.Sqlite

type User = { id: int; login: string }

let createConnection () : IDbConnection =
    new SQLiteConnection($"""Data Source=db.sqlite""")

let config = QueryConfig.Default(createConnection).SqliteDateTimeAsString()
let query = QueryBuilder(config)
let run f = DbCall.Run(createConnection, f)


let getUsers =
    query.Sql("select id,login from users;", Params.Unit, Results.List<User>())

async {
    let! users = getUsers () |> run
    printfn "got users %A" users
    return 0
}
|> Async.RunSynchronously

```

It results in the error
```
System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at lambda_method3(Closure, IDataRecord)
   at <StartupCode$DbFun-Core>.$Results.List@196-10.DbFun.Core.Builders.IResultReader<Microsoft.FSharp.Collections.List<'Result>>.Read(IDataReader reader) in C:\Projekty\FSharp\DbFun\DbFun.Core\Results.fs:line 198
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1139
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1166
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1515
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in /home/dotdev/tmp/dbfunbug/demo.fsx:line 25
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Is the digits only string read as an int ?

**Comment by jacentino** [comment]
Hi rbauduin,

This example works just fine if you change the login column type to TEXT.
I think that sqlite doesn't play well with "string" type.
The users table definition should look like this:

CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, login TEXT)




wt., 29 paź 2024 o 14:05 rbauduin ***@***.***> napisał(a):

**Comment by jacentino** [comment]
Seems that it's rather Sqlite than DbFun issue.

**Comment by rbauduin** [comment]
Better late than never ;-) but for future readers I confirm this was the issue. Using `text` for the column's type avoided this problem. [Column affinity](https://www.sqlite.org/datatype3.html#determination_of_column_affinity) documentation was interesting to read.
An alternative solution might be to use [strict tables](https://www.sqlite.org/stricttables.html) but I haven't tested this.
